{
    'name': 'SPC Free Zone Portal',
    'version': '17.0.1.0.0',
    'category': 'Website',
    'summary': 'SPC Free Zone - Company Management Portal',
    'author': 'Your Company',
    'depends': [
        'base',
        'mail',
        'web',
        'portal',
        'website',
        'account',
        'project',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/mail_template_data.xml',
        'views/portal_templates.xml',
        'views/step2_business_activities.xml',
            'views/step3_company.xml',
            'views/step4_facility.xml',
            'views/step5_visa.xml',
            'views/step6_shareholder.xml',
        'views/step7_manager.xml',
        'views/step10_nature.xml',
        'views/step11_bank.xml',
        'views/step12_docs.xml',
        'views/step13_review.xml',
        'views/nr_steps.xml',
        'views/pa_steps.xml',
        'views/amd_steps.xml',
        'views/va_steps.xml',
        'views/certify_steps.xml',
        'views/ec_steps.xml',
        'views/lr_rn_steps.xml',
            'views/step14_payment.xml',
        'views/step8_9_director_ubo.xml',
        'views/nr_backend_views.xml',
        'views/company_mgmt_backend_views.xml',
        'views/pa_backend_views.xml',
        'views/backend_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
