{
    'name': 'SPC Free Zone Portal',
    'version': '17.0.1.0.0',
    'category': 'Website',
    'summary': 'SPC Free Zone - Company Management Portal',
    'author': 'Your Company',
    'depends': [
        'base',
        'mail',
        'web',
        'portal',
        'website',
        'account',
        'project',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/spc_phone_answering_sequences.xml',
        'data/spc_po_box_sequences.xml',
        'data/spc_movement_report_sequences.xml',
        'data/spc_eid_appointment_sequences.xml',
        'data/sequence_data.xml',
        'data/spc_vip_medical_sequences.xml',
        'data/spc_driving_license_sequences.xml',
        'data/mail_template_data.xml',
        'views/phone_answering_steps.xml',
        'views/po_box_steps.xml',
        'views/movement_report_steps.xml',
        'views/eid_appointment_steps.xml',
        'views/portal_templates.xml',
        'views/step2_business_activities.xml',
            'views/step3_company.xml',
            'views/step4_facility.xml',
            'views/step5_visa.xml',
            'views/step6_shareholder.xml',
        'views/step7_manager.xml',
        'views/step10_nature.xml',
        'views/step11_bank.xml',
        'views/step12_docs.xml',
        'views/step13_review.xml',
        'views/nr_steps.xml',
        'views/pa_steps.xml',
        'views/amd_steps.xml',
        'views/va_steps.xml',
        'views/certify_steps.xml',
        'views/ec_steps.xml',
        'views/lr_rn_steps.xml',
        'views/bl_steps.xml',
        'views/cl_steps.xml',
            'views/step14_payment.xml',
        'views/step8_9_director_ubo.xml',
        'views/backend_views.xml',
        'views/nr_backend_views.xml',
        'views/company_mgmt_backend_views.xml',
        'views/pa_backend_views.xml',
        'views/nma_ml_steps.xml',
        'views/nma_ml_backend_views.xml',
        'views/nma_permit_steps.xml',
        'views/nma_permit_backend_views.xml',
        'views/employee_list_steps.xml',
        'views/employee_list_backend_views.xml',
        'views/facility_mgmt_steps.xml',
        'views/facility_mgmt_backend_views.xml',
        'views/change_of_status_steps.xml',
        'views/emp_mgmt_backend_views.xml',
        'views/dam_steps.xml',
        'views/concierge_backend_views.xml',
        'views/eid_replacement_backend_views.xml',
        'views/eid_replacement_steps.xml',
        'views/vip_medical_company_stamp_dependent_visa_steps.xml',
        'views/driving_license_steps.xml',
        'views/driving_license_backend_views.xml',
        'views/reentry_lease_backend_views.xml',
        'views/reentry_lease_steps.xml',
        'views/medical_meeting_mofa_backend.xml',
        'views/medical_meeting_mofa_steps.xml',
        'views/banking_steps.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
